import React from 'react';

export const DATA_ITEM = [
    {
        id: "01125",
        date: "Сегодня в 16:32",
        departure: "Астана, Казахстан",
        appointment: "Акколь, Казахстан",
        distance: "253",
        typeTransport: "Тент",
        weight: "16",
        volume: "20",
        category: "Мебель",
        price: "83 000"
    },
    {
        id: "01126",
        date: "Сегодня в 17:45",
        departure: "Актобе, Казахстан",
        appointment: "Актау, Казахстан",
        distance: "623",
        typeTransport: "Рефрижератор",
        weight: "25",
        volume: "30",
        category: "Продукты",
        price: "105 000"
    },
    {
        id: "01127",
        date: "Вчера в 14:20",
        departure: "Алматы, Казахстан",
        appointment: "Атырау, Казахстан",
        distance: "1520",
        typeTransport: "Контейнер",
        weight: "40",
        volume: "50",
        category: "Стройматериалы",
        price: "215 000"
    },
    {
        id: "01128",
        date: "Сегодня в 08:10",
        departure: "Караганда, Казахстан",
        appointment: "Костанай, Казахстан",
        distance: "570",
        typeTransport: "Платформа",
        weight: "35",
        volume: "45",
        category: "Химия",
        price: "150 000"
    },
    {
        id: "01129",
        date: "Вчера в 18:55",
        departure: "Кызылорда, Казахстан",
        appointment: "Кокшетау, Казахстан",
        distance: "870",
        typeTransport: "Цистерна",
        weight: "22",
        volume: "25",
        category: "Нефтепродукты",
        price: "95 000"
    },
    {
        id: "01130",
        date: "Сегодня в 11:40",
        departure: "Павлодар, Казахстан",
        appointment: "Петропавловск, Казахстан",
        distance: "430",
        typeTransport: "Бункер",
        weight: "28",
        volume: "30",
        category: "Зерно",
        price: "80 000"
    },
    // {
    //     id: "01131",
    //     date: "Сегодня в 13:15",
    //     departure: "Талдыкорган, Казахстан",
    //     appointment: "Тараз, Казахстан",
    //     distance: "330",
    //     typeTransport: "Тент",
    //     weight: "18",
    //     volume: "22",
    //     category: "Фрукты и овощи",
    //     price: "75 000"
    // },
    // {
    //     id: "01132",
    //     date: "Вчера в 09:30",
    //     departure: "Уральск, Казахстан",
    //     appointment: "Усть-Каменогорск, Казахстан",
    //     distance: "980",
    //     typeTransport: "Фургон",
    //     weight: "38",
    //     volume: "48",
    //     category: "Текстиль",
    //     price: "120 000"
    // },
    // {
    //     id: "01133",
    //     date: "Сегодня в 19:20",
    //     departure: "Шымкент, Казахстан",
    //     appointment: "Шу, Казахстан",
    //     distance: "280",
    //     typeTransport: "Контейнер",
    //     weight: "20",
    //     volume: "24",
    //     category: "Стройматериалы",
    //     price: "95 000"
    // },
    // {
    //     id: "01134",
    //     date: "Сегодня в 10:05",
    //     departure: "Алматы, Казахстан",
    //     appointment: "Актау, Казахстан",
    //     distance: "2800",
    //     typeTransport: "Платформа",
    //     weight: "45",
    //     volume: "55",
    //     category: "Химия",
    //     price: "220 000"
    // },
    // {
    //     id: "01135",
    //     date: "Вчера в 15:20",
    //     departure: "Нур-Султан, Казахстан",
    //     appointment: "Кызылорда, Казахстан",
    //     distance: "1230",
    //     typeTransport: "Цистерна",
    //     weight: "30",
    //     volume: "35",
    //     category: "Нефтепродукты",
    //     price: "110 000"
    // },
    // {
    //     id: "01136",
    //     date: "Сегодня в 08:45",
    //     departure: "Актобе, Казахстан",
    //     appointment: "Алматы, Казахстан",
    //     distance: "1400",
    //     typeTransport: "Тент",
    //     weight: "32",
    //     volume: "40",
    //     category: "Мебель",
    //     price: "170 000"
    // },
    // {
    //     id: "01137",
    //     date: "Сегодня в 12:30",
    //     departure: "Атырау, Казахстан",
    //     appointment: "Уральск, Казахстан",
    //     distance: "480",
    //     typeTransport: "Фургон",
    //     weight: "22",
    //     volume: "28",
    //     category: "Текстиль",
    //     price: "90 000"
    // },
    // {
    //     id: "01138",
    //     date: "Вчера в 11:15",
    //     departure: "Костанай, Казахстан",
    //     appointment: "Астана, Казахстан",
    //     distance: "340",
    //     typeTransport: "Рефрижератор",
    //     weight: "18",
    //     volume: "22",
    //     category: "Продукты",
    //     price: "85 000"
    // },
    // {
    //     id: "01139",
    //     date: "Сегодня в 14:50",
    //     departure: "Кокшетау, Казахстан",
    //     appointment: "Павлодар, Казахстан",
    //     distance: "630",
    //     typeTransport: "Бункер",
    //     weight: "26",
    //     volume: "32",
    //     category: "Зерно",
    //     price: "95 000"
    // },
    // {
    //     id: "01140",
    //     date: "Сегодня в 17:30",
    //     departure: "Тараз, Казахстан",
    //     appointment: "Талдыкорган, Казахстан",
    //     distance: "270",
    //     typeTransport: "Контейнер",
    //     weight: "19",
    //     volume: "25",
    //     category: "Стройматериалы",
    //     price: "88 000"
    // },
];
